### PR TITLE
hash and json fix

### PR DESCRIPTION
**Pull request by lantonic**
Fixed errors with newer versions of guile-json (tested with 3.1.0) as it apparently now works with alists instead of hash tables and also cannot serialize empty objects.

### CODE REVIEW

**Comment by jerry40** [comment]
Hi! Thanks for your work! About alist-ref, we can use any of these functions: assq-ref , assv-ref, assoc-ref listed there https://www.gnu.org/software/guile/manual/html_node/Retrieving-Alist-Entries.html#Retrieving-Alist-Entries , what do you think?

**Comment by lantonic** [comment]
You're absolutely right, I was in a hurry to get it working and completely missed those. I've changed it so it uses `assoc-ref`.
Also I've fixed the issue of the kernel breaking on error, caused by guile-json now needing a vector to produce a JSON array, instead of a list. This, in turn led me to another issue:
`json.decoder.JSONDecodeError: Invalid control character at: line 1 column 127 (char 126)
` reported by the Jupyter client, caused by the colorized `error-key` string inserted into `stacktrace`. For now, I've fixed it by removing `colorize` as I don't have a better idea.

On an unrelated note, the kernel seems rather slow compared to other Jupyter kernels (I've personally used Python, JavaScript, Octave, Go and Racket kernels). Would this be due to some limitations within Guile, or do you think there is room for optimisation?

**Comment by jerry40** [comment]
Thanks! I have not executed it recently, so I just missed all these errors. About slowness I am not sure... I just send commands to guile, perhaps we can do some tests - run commands in guile interpreter and in the kernel to compare results.

**Comment by lantonic** [comment]
Alright, I'll try and do some tests when i can. I'll open an issue if I find anything meaningful.
Also, thanks for taking the time to write this kernel! Jupyter kernels are a great way to learn languages (as I'm currently doing with Guile and Scheme in general).

**Comment by jerry40** [comment]
Thank you for using it! Ok, let's discuss your tests results if you'll find anything interesting.

**Pull request merged**
